import { useState, type FormEvent, type ReactNode } from 'react'
import { Navigate, NavLink, Outlet, Route, Routes, useNavigate, useOutletContext, useParams, useSearchParams } from 'react-router-dom'
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { auth, get, getPage, message, patch, post, type Envelope, type User } from './api'

type Item = Record<string, unknown> & { id: string; version?: number; title?: string; name?: string; status?: string; code?: string; issue_number?: string }
type Overview = { issues?: { open?: unknown; critical?: unknown }; clients?: { active?: unknown }; follow_ups?: { pending?: unknown; overdue?: unknown }; handoffs?: { pending?: unknown } }
const client = new QueryClient({ defaultOptions: { queries: { retry: false } } })
const label = (x: Item) => x.title || x.name || x.code || x.issue_number || x.id
const permissions = (user: User | undefined, permission: string) => !!user?.permissions.includes(permission)
const number = (value: unknown) => typeof value === 'number' && Number.isFinite(value) ? value : 0

function State({ query, children }: { query: ReturnType<typeof useQuery<Item[]>>; children: (items: Item[]) => ReactNode }) {
  if (query.isPending) return <p role="status">Loading...</p>
  if (query.isError) return <p role="alert">{message(query.error)}</p>
  return query.data?.length ? <>{children(query.data)}</> : <p>No records.</p>
}
function Login() {
  const nav = useNavigate(); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: ({ email, password }: { email: string; password: string }) => auth.login(email, password), onSuccess: () => nav('/dashboard') })
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); setError(''); mutation.mutate({ email: String(data.get('email')), password: String(data.get('password')) }, { onError: e => setError(message(e)) }) }
  return <main className="login"><form onSubmit={submit} className="card"><p className="eyebrow">ClientOps</p><h1>Sign in</h1><label>Email<input name="email" type="email" required autoComplete="email" /></label><label>Password<input name="password" type="password" required minLength={8} autoComplete="current-password" /></label>{error && <p role="alert">{error}</p>}<button disabled={mutation.isPending}>{mutation.isPending ? 'Signing in...' : 'Sign in'}</button></form></main>
}
function Shell() {
  const nav = useNavigate(); const me = useQuery({ queryKey: ['me'], queryFn: auth.me }); const logout = useMutation({ mutationFn: auth.logout, onSuccess: () => { client.clear(); nav('/login') } })
  if (me.isPending) return <main><p role="status">Loading session...</p></main>
  if (me.isError) return <Navigate to="/login" replace />
  return <div className="app-shell"><header className="app-header"><NavLink className="brand" to="/dashboard">ClientOps</NavLink><nav aria-label="Main navigation">{['dashboard', 'clients', 'issues', 'releases', 'handoffs', 'follow-ups'].map(x => <NavLink key={x} to={`/${x}`}>{x.replace('-', ' ')}</NavLink>)}</nav><div className="account"><span>{me.data.name}</span><button onClick={() => logout.mutate()} disabled={logout.isPending}>Sign out</button></div></header><main><Outlet context={me.data} /></main></div>
}
function Dashboard() {
  const query = useQuery<Overview>({ queryKey: ['dashboard', 'overview'], queryFn: () => get('/dashboard/overview') })
  if (query.isPending) return <section className="dashboard"><p role="status">Loading dashboard...</p></section>
  if (query.isError) return <section className="dashboard"><h1>Dashboard</h1><p role="alert">{message(query.error)}</p></section>
  const overview = query.data || {}
  const metrics = [
    ['Open issues', number(overview.issues?.open), '/issues', 'Issues not closed or cancelled'],
    ['Critical issues', number(overview.issues?.critical), '/issues', 'Open issues requiring attention'],
    ['Active clients', number(overview.clients?.active), '/clients', 'Clients in active service'],
    ['Pending handoffs', number(overview.handoffs?.pending), '/handoffs', 'Release impacts awaiting operations'],
    ['Pending follow-ups', number(overview.follow_ups?.pending), '/follow-ups', 'Client actions still open'],
    ['Overdue follow-ups', number(overview.follow_ups?.overdue), '/follow-ups', 'Follow-ups past their due date'],
  ]
  return <section className="dashboard"><div className="dashboard-heading"><p className="eyebrow">Operational overview</p><h1>Keep delivery visible.</h1><p>Track work from client report through operational completion.</p></div><div className="metric-grid">{metrics.map(([label, value, to, detail]) => <NavLink key={label} className="metric-card" to={to as string}><span>{label}</span><strong>{value}</strong><small>{detail}</small></NavLink>)}</div></section>
}
function List({ path, title, create, render }: { path: string; title: string; create?: ReactNode; render?: (x: Item) => ReactNode }) {
  const q = useQuery<Item[]>({ queryKey: [path], queryFn: () => get(path) }); return <section><div className="title"><h1>{title}</h1>{create}</div><State query={q}>{items => <ul className="records">{items.map(x => <li key={x.id}>{render?.(x) || <><strong>{label(x)}</strong><small>{x.status || ''}</small></>}</li>)}</ul>}</State></section>
}
function Create({ path, fields, done }: { path: string; fields: { name: string; label: string; type?: string; options?: string[] }[]; done?: () => void }) {
  const cache = useQueryClient(); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: (data: Record<string, unknown>) => post(path, data), onSuccess: () => { cache.invalidateQueries({ queryKey: [path] }); done?.() } })
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const data = Object.fromEntries(form); setError(''); mutation.mutate(data, { onError: e => setError(message(e)) }) }
  return <form onSubmit={submit} className="card create">{fields.map(f => <label key={f.name}>{f.label}{f.options ? <select name={f.name} required><option value="">Select</option>{f.options.map(o => <option key={o}>{o}</option>)}</select> : <input name={f.name} type={f.type || 'text'} required />}</label>)}{error && <p role="alert">{error}</p>}<button disabled={mutation.isPending}>{mutation.isPending ? 'Saving...' : 'Create'}</button></form>
}
type Client = Item & { code?: string; type?: string; province?: string; city?: string; address?: string }
type ClientDetail = { client: Client; primary_contact?: Item; owners?: Item[]; summary?: Record<string, unknown>; health?: Item }
type Page<T> = { data: T[] }
const clientTypes = ['ELEMENTARY', 'JUNIOR_HIGH', 'SENIOR_HIGH', 'VOCATIONAL', 'OTHER']
const clientStatuses = ['ACTIVE', 'ONBOARDING', 'INACTIVE']
function clientPage(url: string) { return get<Client[]>(url).then(data => ({ data }) as Page<Client>) }
function Clients() {
  const user = useOutletContext<User>(); const [params, setParams] = useSearchParams(); const [open, setOpen] = useState(false)
  const query = useQuery<Page<Client>>({ queryKey: ['clients', params.toString()], queryFn: () => clientPage(`/clients?${params}`) })
  const canCreate = permissions(user, 'client.create'); const page = Number(params.get('page') || 1)
  function filters(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const next = new URLSearchParams(); new FormData(e.currentTarget).forEach((value, key) => { if (value) next.set(key, String(value)) }); next.set('page', '1'); setParams(next) }
  function move(next: number) { const p = new URLSearchParams(params); p.set('page', String(next)); setParams(p) }
  return <section className="clients-workspace"><div className="title"><div><p className="eyebrow">Client directory</p><h1>Client workspace</h1></div>{canCreate && <button onClick={() => setOpen(!open)}>{open ? 'Cancel' : 'New client'}</button>}</div>
    <form className="client-filters" onSubmit={filters}><label>Search<input name="search" defaultValue={params.get('search') || ''} placeholder="Name or code" /></label><label>Status<select name="status" defaultValue={params.get('status') || ''}><option value="">All statuses</option>{clientStatuses.map(x => <option key={x}>{x}</option>)}</select></label><label>Type<select name="type" defaultValue={params.get('type') || ''}><option value="">All types</option>{clientTypes.map(x => <option key={x}>{x}</option>)}</select></label><button>Apply filters</button></form>
    {open && <Create path="/clients" done={() => { setOpen(false); query.refetch() }} fields={[{ name: 'code', label: 'Code' }, { name: 'name', label: 'Name' }, { name: 'type', label: 'Type', options: clientTypes }]} />}
    {query.isPending ? <p role="status">Loading clients...</p> : query.isError ? <p role="alert">{message(query.error)}</p> : !query.data?.data.length ? <p>No clients match these filters.</p> : <div className="client-table" role="list">{query.data.data.map(x => <NavLink role="listitem" key={x.id} to={`/clients/${x.id}`}><span><strong>{x.name}</strong><small>{x.code}</small></span><span>{x.type?.replaceAll('_', ' ')}</span><span className={`status status-${String(x.status).toLowerCase()}`}>{x.status}</span><span>{x.city || x.province || 'Location unavailable'}</span></NavLink>)}</div>}
    <div className="pagination"><span>Page {page}</span><button disabled={page === 1} onClick={() => move(page - 1)}>Previous</button><button disabled={(query.data?.data.length || 0) < 20} onClick={() => move(page + 1)}>Next</button></div>
  </section>
}
function ClientDetail() {
  const { id = '' } = useParams(); const user = useOutletContext<User>(); const cache = useQueryClient(); const [editing, setEditing] = useState(false); const [archiving, setArchiving] = useState(false); const [error, setError] = useState('')
  const detail = useQuery<ClientDetail>({ queryKey: ['client', id], queryFn: () => get(`/clients/${id}`) }); const contacts = useQuery<Item[]>({ queryKey: ['client', id, 'contacts'], queryFn: () => get(`/clients/${id}/contacts`) }); const owners = useQuery<Item[]>({ queryKey: ['client', id, 'owners'], queryFn: () => get(`/clients/${id}/owners`) }); const users = useQuery<User[]>({ queryKey: ['users'], queryFn: () => get('/users'), enabled: permissions(user, 'client.assign_owner') })
  function refresh() { cache.invalidateQueries({ queryKey: ['client', id] }); cache.invalidateQueries({ queryKey: ['clients'] }) }
  const update = useMutation({ mutationFn: (data: Record<string, unknown>) => patch(`/clients/${id}`, data), onSuccess: () => { setEditing(false); setError(''); refresh() }, onError: e => setError(message(e)) })
  const archive = useMutation({ mutationFn: () => post(`/clients/${id}/archive`, { version: detail.data?.client.version }), onSuccess: () => { refresh(); setArchiving(false) }, onError: e => setError(message(e)) })
  const contact = useMutation({ mutationFn: (data: Record<string, unknown>) => post(`/clients/${id}/contacts`, data), onSuccess: () => { cache.invalidateQueries({ queryKey: ['client', id, 'contacts'] }); setError('') }, onError: e => setError(message(e)) })
  const primary = useMutation({ mutationFn: (new_owner_id: string) => post(`/clients/${id}/change-primary-owner`, { new_owner_id }), onSuccess: () => { cache.invalidateQueries({ queryKey: ['client', id, 'owners'] }); refresh() }, onError: e => setError(message(e)) })
  if (detail.isPending) return <p role="status">Loading client...</p>; if (detail.isError || !detail.data) return <p role="alert">{message(detail.error)}</p>
  const client = detail.data.client; const canUpdate = permissions(user, 'client.update'); const canArchive = permissions(user, 'client.archive'); const canOwners = permissions(user, 'client.assign_owner')
  function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); update.mutate({ ...Object.fromEntries(new FormData(e.currentTarget)), version: client.version }) }
  function addContact(e: FormEvent<HTMLFormElement>) { e.preventDefault(); contact.mutate(Object.fromEntries(new FormData(e.currentTarget))) }
  return <section className="client-detail"><NavLink className="back" to="/clients">All clients</NavLink><div className="detail-heading"><div><p className="eyebrow">{client.code}</p><h1>{client.name}</h1><p>{client.type?.replaceAll('_', ' ')} · {client.status}</p></div><div className="detail-actions">{canUpdate && <button onClick={() => setEditing(!editing)}>{editing ? 'Cancel edit' : 'Edit client'}</button>}{canArchive && client.status !== 'INACTIVE' && <button className="danger" onClick={() => setArchiving(true)}>Archive</button>}</div></div>
    {error && <p role="alert">{error}</p>}{editing && <form className="card client-edit" onSubmit={save}><label>Name<input name="name" required defaultValue={client.name} /></label><label>Type<select name="type" defaultValue={client.type}>{clientTypes.map(x => <option key={x}>{x}</option>)}</select></label><label>Status<select name="status" defaultValue={client.status}>{clientStatuses.map(x => <option key={x}>{x}</option>)}</select></label><label>Province<input name="province" defaultValue={client.province} /></label><label>City<input name="city" defaultValue={client.city} /></label><label>Address<input name="address" defaultValue={client.address} /></label><button disabled={update.isPending}>{update.isPending ? 'Saving...' : 'Save changes'}</button></form>}
    <div className="detail-grid"><section className="panel"><h2>Operational picture</h2><dl>{Object.entries(detail.data.summary || {}).map(([k, v]) => <div key={k}><dt>{k.replaceAll('_', ' ')}</dt><dd>{String(v)}</dd></div>)}{detail.data.health && <div><dt>Health</dt><dd>{label(detail.data.health)} {String(detail.data.health.score || '')}</dd></div>}</dl></section><section className="panel"><h2>Owners</h2>{owners.isPending ? <p>Loading...</p> : owners.data?.length ? <ul className="compact-list">{owners.data.map(x => <li key={x.id}><strong>{String(x.user_name || x.name || x.user_id)}</strong><small>{String(x.owner_type)}</small></li>)}</ul> : <p>No owners assigned.</p>}{canOwners && <form onSubmit={e => { e.preventDefault(); const owner = String(new FormData(e.currentTarget).get('new_owner_id')); if (owner) primary.mutate(owner) }}><label>Primary owner<select name="new_owner_id" required defaultValue=""><option value="" disabled>Select user</option>{users.data?.map(x => <option key={x.id} value={x.id}>{x.name} ({x.email})</option>)}</select></label><button disabled={primary.isPending || users.isPending}>{primary.isPending ? 'Changing...' : 'Change primary owner'}</button>{users.isError && <p role="alert">Users unavailable: {message(users.error)}</p>}</form>}</section><section className="panel"><h2>Contacts</h2>{contacts.isPending ? <p>Loading...</p> : contacts.data?.length ? <ul className="compact-list">{contacts.data.map(x => <li key={x.id}><strong>{label(x)}</strong><small>{String(x.email || x.phone || '')}</small></li>)}</ul> : <p>No contacts recorded.</p>}{canUpdate && <form onSubmit={addContact}><label>Name<input name="name" required /></label><label>Email<input name="email" type="email" /></label><label>Phone<input name="phone" /></label><label>Role<input name="role" /></label><button disabled={contact.isPending}>{contact.isPending ? 'Adding...' : 'Add contact'}</button></form>}</section></div>
    {archiving && <div className="dialog-backdrop" role="presentation"><section className="dialog" role="alertdialog" aria-modal="true" aria-labelledby="archive-title"><h2 id="archive-title">Archive {client.name}?</h2><p>Archived clients leave active service. This action is traceable.</p><div><button className="danger" autoFocus disabled={archive.isPending} onClick={() => archive.mutate()}>{archive.isPending ? 'Archiving...' : 'Archive client'}</button><button className="secondary" onClick={() => setArchiving(false)}>Cancel</button></div></section></div>}
  </section>
}
type Issue = Item & { client_id: string; assignee_id?: string; release_id?: string; description?: string; category?: string; resolution_summary?: string }
type History = Item & { from_status?: string; to_status?: string; changed_by?: string; reason?: string; created_at?: string }
const severities = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
const issueStatuses = ['REPORTED', 'TRIAGED', 'INVESTIGATING', 'IN_DEVELOPMENT', 'QA', 'RELEASED', 'FOLLOW_UP', 'CLOSED', 'REOPENED']
function Issues() {
  const user = useOutletContext<User>(); const [params, setParams] = useSearchParams(); const [open, setOpen] = useState(false)
  const issues = useQuery<Envelope<Issue[]>>({ queryKey: ['issues', params.toString()], queryFn: () => getPage<Issue[]>(`/issues?${params}`) })
  const clients = useQuery<Client[]>({ queryKey: ['clients', 'issue-selector'], queryFn: () => get('/clients?limit=100') })
  function filters(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const next = new URLSearchParams(); new FormData(e.currentTarget).forEach((v, k) => { if (v) next.set(k, String(v)) }); next.set('page', '1'); setParams(next) }
  function move(page: number) { const next = new URLSearchParams(params); next.set('page', String(page)); setParams(next) }
  function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); post('/issues', data).then(() => { setOpen(false); issues.refetch() }) }
  return <section className="clients-workspace"><div className="title"><div><p className="eyebrow">Delivery workspace</p><h1>Issues</h1></div>{permissions(user, 'issue.create') && <button onClick={() => setOpen(!open)}>{open ? 'Cancel' : 'New issue'}</button>}</div>
    <form className="client-filters" onSubmit={filters}><label>Search<input name="search" defaultValue={params.get('search') || ''} placeholder="Title or issue number" /></label><label>Status<select name="status" defaultValue={params.get('status') || ''}><option value="">All statuses</option>{issueStatuses.map(x => <option key={x}>{x}</option>)}</select></label><label>Severity<select name="severity" defaultValue={params.get('severity') || ''}><option value="">All severities</option>{severities.map(x => <option key={x}>{x}</option>)}</select></label><button>Apply filters</button></form>
    {open && <form className="card create" onSubmit={create}><label>Client<select name="client_id" required defaultValue="" disabled={clients.isPending || clients.isError}><option value="" disabled>{clients.isPending ? 'Loading clients...' : 'Select client'}</option>{clients.data?.map(x => <option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></label><label>Title<input name="title" required /></label><label>Description<textarea name="description" required /></label><label>Severity<select name="severity" defaultValue="MEDIUM">{severities.map(x => <option key={x}>{x}</option>)}</select></label><label>Category<input name="category" /></label><button>Create issue</button>{clients.isError && <p role="alert">{message(clients.error)}</p>}</form>}
    {issues.isPending ? <p role="status">Loading issues...</p> : issues.isError ? <p role="alert">{message(issues.error)}</p> : !issues.data?.data.length ? <p>No issues match these filters.</p> : <div className="client-table" role="list">{issues.data.data.map(x => <NavLink role="listitem" key={x.id} to={`/issues/${x.id}`}><span><strong>{String(x.title || '')}</strong><small>{String(x.issue_number || '')}</small></span><span>{String(x.status || '')}</span><span className="status">{String(x.severity || '')}</span><span>{String(x.category || 'Uncategorized')}</span></NavLink>)}</div>}
    <div className="pagination"><span>Page {issues.data?.meta?.page || Number(params.get('page') || 1)} of {issues.data?.meta?.total_pages || 1}</span><button disabled={!issues.data?.meta || issues.data.meta.page <= 1} onClick={() => move((issues.data?.meta?.page || 1) - 1)}>Previous</button><button disabled={!issues.data?.meta || issues.data.meta.page >= issues.data.meta.total_pages} onClick={() => move((issues.data?.meta?.page || 1) + 1)}>Next</button></div>
  </section>
}
const actionPermissions: Record<string, string> = { assign: 'issue.assign', triage: 'issue.triage', 'start-investigation': 'issue.investigate', 'start-development': 'issue.start_development', 'mark-qa': 'issue.mark_qa', 'qa-failed': 'issue.mark_qa', 'mark-released': 'issue.mark_released', 'start-follow-up': 'issue.follow_up', close: 'issue.close', reopen: 'issue.reopen' }
const statusActions: Record<string, string[]> = { REPORTED: ['assign', 'triage'], TRIAGED: ['assign', 'start-investigation'], INVESTIGATING: ['assign', 'start-development'], IN_DEVELOPMENT: ['mark-qa'], QA: ['qa-failed', 'mark-released'], RELEASED: ['start-follow-up'], FOLLOW_UP: ['close'], CLOSED: ['reopen'] }
function IssueDetail() {
  const { id = '' } = useParams(); const user = useOutletContext<User>(); const cache = useQueryClient(); const [editing, setEditing] = useState(false); const [selected, setSelected] = useState(''); const [error, setError] = useState('')
  const q = useQuery<Issue>({ queryKey: ['issue', id], queryFn: () => get(`/issues/${id}`) }); const history = useQuery<History[]>({ queryKey: ['issue', id, 'history'], queryFn: () => get(`/issues/${id}/history`) }); const clients = useQuery<Client[]>({ queryKey: ['clients', 'issue-selector'], queryFn: () => get('/clients?limit=100') }); const users = useQuery<User[]>({ queryKey: ['users', 'issue-assignees'], queryFn: () => get('/users'), enabled: permissions(user, 'issue.assign') }); const releases = useQuery<Item[]>({ queryKey: ['releases', 'issue-selector'], queryFn: () => get('/releases'), enabled: selected === 'mark-released' })
  function refresh() { cache.invalidateQueries({ queryKey: ['issue', id] }); cache.invalidateQueries({ queryKey: ['issue', id, 'history'] }); cache.invalidateQueries({ queryKey: ['issues'] }) }
  const update = useMutation({ mutationFn: (data: Record<string, unknown>) => patch(`/issues/${id}`, data), onSuccess: () => { setEditing(false); setError(''); refresh() }, onError: e => setError(message(e)) })
  const action = useMutation({ mutationFn: ({ name, data }: { name: string; data: Record<string, unknown> }) => post(`/issues/${id}/${name}`, data), onSuccess: () => { setSelected(''); setError(''); refresh() }, onError: e => setError(message(e)) })
  if (q.isPending) return <p role="status">Loading issue...</p>; if (q.isError || !q.data) return <p role="alert">{message(q.error)}</p>
  const issue = q.data; const clientName = clients.data?.find(x => x.id === issue.client_id)?.name || issue.client_id; const assignee = users.data?.find(x => x.id === issue.assignee_id)?.name || issue.assignee_id || 'Unassigned'; const release = releases.data?.find(x => x.id === issue.release_id); const actions = (statusActions[issue.status || ''] || []).filter(x => permissions(user, actionPermissions[x]))
  function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); update.mutate({ ...Object.fromEntries(new FormData(e.currentTarget)), version: issue.version }) }
  function submitAction(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if ((selected === 'close' || selected === 'reopen') && !window.confirm(`${selected === 'close' ? 'Close' : 'Reopen'} this issue?`)) return; const data = Object.fromEntries(new FormData(e.currentTarget)); action.mutate({ name: selected, data: { ...data, version: issue.version } }) }
  return <section className="client-detail"><NavLink className="back" to="/issues">All issues</NavLink><div className="detail-heading"><div><p className="eyebrow">{String(issue.issue_number || '')}</p><h1>{String(issue.title || '')}</h1><p>{String(issue.status || '')} · {String(issue.severity || '')}</p></div>{permissions(user, 'issue.update') && <div className="detail-actions"><button onClick={() => setEditing(!editing)}>{editing ? 'Cancel edit' : 'Edit issue'}</button></div>}</div>{error && <p role="alert">{error}</p>}
    {editing && <form className="card client-edit" onSubmit={save}><label>Title<input name="title" required defaultValue={String(issue.title || '')} /></label><label>Description<textarea name="description" required defaultValue={String(issue.description || '')} /></label><label>Category<input name="category" defaultValue={String(issue.category || '')} /></label><label>Severity<select name="severity" defaultValue={String(issue.severity || '')}>{severities.map(x => <option key={x}>{x}</option>)}</select></label><button disabled={update.isPending}>{update.isPending ? 'Saving...' : 'Save changes'}</button></form>}
    <div className="detail-grid"><section className="panel"><h2>Issue details</h2><dl><div><dt>Client</dt><dd>{clientName}</dd></div><div><dt>Assignee</dt><dd>{assignee}</dd></div><div><dt>Release</dt><dd>{release ? label(release) : issue.release_id || 'Not released'}</dd></div><div><dt>Category</dt><dd>{String(issue.category || 'Uncategorized')}</dd></div><div><dt>Resolution</dt><dd>{String(issue.resolution_summary || 'None')}</dd></div><div><dt>Version</dt><dd>{String(issue.version || '')}</dd></div></dl></section><section className="panel"><h2>Workflow actions</h2>{actions.length ? <div className="detail-actions">{actions.map(x => <button key={x} onClick={() => setSelected(selected === x ? '' : x)}>{x.replaceAll('-', ' ')}</button>)}</div> : <p>No permitted actions for this status.</p>}{selected && <form onSubmit={submitAction}><h3>{selected.replaceAll('-', ' ')}</h3>{selected === 'assign' && <label>Assignee<select name="assignee_id" required defaultValue=""><option value="" disabled>Select user</option>{users.data?.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}{selected === 'triage' && <><label>Category<input name="category" required defaultValue={String(issue.category || '')} /></label><label>Severity<select name="severity" required defaultValue={String(issue.severity || 'MEDIUM')}>{severities.map(x => <option key={x}>{x}</option>)}</select></label></>}{selected === 'mark-released' && <label>Release<select name="release_id" required defaultValue=""><option value="" disabled>{releases.isPending ? 'Loading releases...' : 'Select release'}</option>{releases.data?.map(x => <option key={x.id} value={x.id}>{label(x)}</option>)}</select></label>}{['qa-failed', 'close', 'reopen'].includes(selected) && <label>{selected === 'close' ? 'Resolution summary' : 'Reason'}<textarea name={selected === 'close' ? 'resolution_summary' : 'reason'} required={selected === 'reopen'} /></label>}<button disabled={action.isPending || (selected === 'mark-released' && releases.isPending)}>{action.isPending ? 'Updating...' : 'Confirm action'}</button></form>}{action.isError && <p role="alert">{message(action.error)}</p>}</section><section className="panel"><h2>History</h2>{history.isPending ? <p>Loading...</p> : history.isError ? <p role="alert">{message(history.error)}</p> : history.data?.length ? <ul className="compact-list">{history.data.map(x => <li key={x.id}><strong>{String(x.from_status || 'Created')} to {String(x.to_status || '')}</strong><small>{String(x.reason || x.changed_by || '')} {x.created_at ? `· ${new Date(String(x.created_at)).toLocaleString()}` : ''}</small></li>)}</ul> : <p>No history recorded.</p>}</section></div>
  </section>
}
function Releases() { const [open, setOpen] = useState(false); return <><List path="/releases" title="Releases" create={<button onClick={() => setOpen(!open)}>New release</button>} />{open && <Create path="/releases" done={() => setOpen(false)} fields={[{ name: 'version', label: 'Version' }, { name: 'title', label: 'Title' }, { name: 'summary', label: 'Summary' }]} />}</> }
function Operations({ followUps = false }: { followUps?: boolean }) { const path = followUps ? '/follow-ups' : '/handoffs'; return <List path={path} title={followUps ? 'Follow-ups' : 'Handoffs'} render={x => <><strong>{label(x)}</strong><small>{String(x.status || '')}</small></>} /> }
export default function App() { return <QueryClientProvider client={client}><Routes><Route path="/login" element={<Login />} /><Route element={<Shell />}><Route path="/dashboard" element={<Dashboard />} /><Route path="/clients" element={<Clients />} /><Route path="/clients/:id" element={<ClientDetail />} /><Route path="/issues" element={<Issues />} /><Route path="/issues/:id" element={<IssueDetail />} /><Route path="/releases" element={<Releases />} /><Route path="/handoffs" element={<Operations />} /><Route path="/follow-ups" element={<Operations followUps />} /></Route><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></QueryClientProvider> }
