import { useState, type FormEvent, type ReactNode } from 'react'
import { Navigate, NavLink, Outlet, Route, Routes, useNavigate, useOutletContext, useParams, useSearchParams } from 'react-router-dom'
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { auth, get, message, patch, post, type User } from './api'

type Item = Record<string, unknown> & { id: string; version?: number; title?: string; name?: string; status?: string; code?: string; issue_number?: string }
type Overview = { issues?: { open?: unknown; critical?: unknown }; clients?: { active?: unknown }; follow_ups?: { pending?: unknown; overdue?: unknown }; handoffs?: { pending?: unknown } }
const client = new QueryClient({ defaultOptions: { queries: { retry: false } } })
const label = (x: Item) => x.title || x.name || x.code || x.issue_number || x.id
const permissions = (user: User | undefined, permission: string) => !!user?.permissions.includes(permission)
const number = (value: unknown) => typeof value === 'number' && Number.isFinite(value) ? value : 0

function State({ query, children }: { query: ReturnType<typeof useQuery<Item[]>>; children: (items: Item[]) => ReactNode }) {
  if (query.isPending) return <p role="status">Loading...</p>
  if (query.isError) return <p role="alert">{message(query.error)}</p>
  return query.data?.length ? <>{children(query.data)}</> : <p>No records.</p>
}
function Login() {
  const nav = useNavigate(); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: ({ email, password }: { email: string; password: string }) => auth.login(email, password), onSuccess: () => nav('/dashboard') })
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); setError(''); mutation.mutate({ email: String(data.get('email')), password: String(data.get('password')) }, { onError: e => setError(message(e)) }) }
  return <main className="login"><form onSubmit={submit} className="card"><p className="eyebrow">ClientOps</p><h1>Sign in</h1><label>Email<input name="email" type="email" required autoComplete="email" /></label><label>Password<input name="password" type="password" required minLength={8} autoComplete="current-password" /></label>{error && <p role="alert">{error}</p>}<button disabled={mutation.isPending}>{mutation.isPending ? 'Signing in...' : 'Sign in'}</button></form></main>
}
function Shell() {
  const nav = useNavigate(); const me = useQuery({ queryKey: ['me'], queryFn: auth.me }); const logout = useMutation({ mutationFn: auth.logout, onSuccess: () => { client.clear(); nav('/login') } })
  if (me.isPending) return <main><p role="status">Loading session...</p></main>
  if (me.isError) return <Navigate to="/login" replace />
  return <div className="app-shell"><header className="app-header"><NavLink className="brand" to="/dashboard">ClientOps</NavLink><nav aria-label="Main navigation">{['dashboard', 'clients', 'issues', 'releases', 'handoffs', 'follow-ups'].map(x => <NavLink key={x} to={`/${x}`}>{x.replace('-', ' ')}</NavLink>)}</nav><div className="account"><span>{me.data.name}</span><button onClick={() => logout.mutate()} disabled={logout.isPending}>Sign out</button></div></header><main><Outlet context={me.data} /></main></div>
}
function Dashboard() {
  const query = useQuery<Overview>({ queryKey: ['dashboard', 'overview'], queryFn: () => get('/dashboard/overview') })
  if (query.isPending) return <section className="dashboard"><p role="status">Loading dashboard...</p></section>
  if (query.isError) return <section className="dashboard"><h1>Dashboard</h1><p role="alert">{message(query.error)}</p></section>
  const overview = query.data || {}
  const metrics = [
    ['Open issues', number(overview.issues?.open), '/issues', 'Issues not closed or cancelled'],
    ['Critical issues', number(overview.issues?.critical), '/issues', 'Open issues requiring attention'],
    ['Active clients', number(overview.clients?.active), '/clients', 'Clients in active service'],
    ['Pending handoffs', number(overview.handoffs?.pending), '/handoffs', 'Release impacts awaiting operations'],
    ['Pending follow-ups', number(overview.follow_ups?.pending), '/follow-ups', 'Client actions still open'],
    ['Overdue follow-ups', number(overview.follow_ups?.overdue), '/follow-ups', 'Follow-ups past their due date'],
  ]
  return <section className="dashboard"><div className="dashboard-heading"><p className="eyebrow">Operational overview</p><h1>Keep delivery visible.</h1><p>Track work from client report through operational completion.</p></div><div className="metric-grid">{metrics.map(([label, value, to, detail]) => <NavLink key={label} className="metric-card" to={to as string}><span>{label}</span><strong>{value}</strong><small>{detail}</small></NavLink>)}</div></section>
}
function List({ path, title, create, render }: { path: string; title: string; create?: ReactNode; render?: (x: Item) => ReactNode }) {
  const q = useQuery<Item[]>({ queryKey: [path], queryFn: () => get(path) }); return <section><div className="title"><h1>{title}</h1>{create}</div><State query={q}>{items => <ul className="records">{items.map(x => <li key={x.id}>{render?.(x) || <><strong>{label(x)}</strong><small>{x.status || ''}</small></>}</li>)}</ul>}</State></section>
}
function Create({ path, fields, done }: { path: string; fields: { name: string; label: string; type?: string; options?: string[] }[]; done?: () => void }) {
  const cache = useQueryClient(); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: (data: Record<string, unknown>) => post(path, data), onSuccess: () => { cache.invalidateQueries({ queryKey: [path] }); done?.() } })
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const data = Object.fromEntries(form); setError(''); mutation.mutate(data, { onError: e => setError(message(e)) }) }
  return <form onSubmit={submit} className="card create">{fields.map(f => <label key={f.name}>{f.label}{f.options ? <select name={f.name} required><option value="">Select</option>{f.options.map(o => <option key={o}>{o}</option>)}</select> : <input name={f.name} type={f.type || 'text'} required />}</label>)}{error && <p role="alert">{error}</p>}<button disabled={mutation.isPending}>{mutation.isPending ? 'Saving...' : 'Create'}</button></form>
}
type Client = Item & { code?: string; type?: string; province?: string; city?: string; address?: string }
type ClientDetail = { client: Client; primary_contact?: Item; owners?: Item[]; summary?: Record<string, unknown>; health?: Item }
type Page<T> = { data: T[] }
const clientTypes = ['ELEMENTARY', 'JUNIOR_HIGH', 'SENIOR_HIGH', 'VOCATIONAL', 'OTHER']
const clientStatuses = ['ACTIVE', 'ONBOARDING', 'INACTIVE']
function clientPage(url: string) { return get<Client[]>(url).then(data => ({ data }) as Page<Client>) }
function Clients() {
  const user = useOutletContext<User>(); const [params, setParams] = useSearchParams(); const [open, setOpen] = useState(false)
  const query = useQuery<Page<Client>>({ queryKey: ['clients', params.toString()], queryFn: () => clientPage(`/clients?${params}`) })
  const canCreate = permissions(user, 'client.create'); const page = Number(params.get('page') || 1)
  function filters(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const next = new URLSearchParams(); new FormData(e.currentTarget).forEach((value, key) => { if (value) next.set(key, String(value)) }); next.set('page', '1'); setParams(next) }
  function move(next: number) { const p = new URLSearchParams(params); p.set('page', String(next)); setParams(p) }
  return <section className="clients-workspace"><div className="title"><div><p className="eyebrow">Client directory</p><h1>Client workspace</h1></div>{canCreate && <button onClick={() => setOpen(!open)}>{open ? 'Cancel' : 'New client'}</button>}</div>
    <form className="client-filters" onSubmit={filters}><label>Search<input name="search" defaultValue={params.get('search') || ''} placeholder="Name or code" /></label><label>Status<select name="status" defaultValue={params.get('status') || ''}><option value="">All statuses</option>{clientStatuses.map(x => <option key={x}>{x}</option>)}</select></label><label>Type<select name="type" defaultValue={params.get('type') || ''}><option value="">All types</option>{clientTypes.map(x => <option key={x}>{x}</option>)}</select></label><button>Apply filters</button></form>
    {open && <Create path="/clients" done={() => { setOpen(false); query.refetch() }} fields={[{ name: 'code', label: 'Code' }, { name: 'name', label: 'Name' }, { name: 'type', label: 'Type', options: clientTypes }]} />}
    {query.isPending ? <p role="status">Loading clients...</p> : query.isError ? <p role="alert">{message(query.error)}</p> : !query.data?.data.length ? <p>No clients match these filters.</p> : <div className="client-table" role="list">{query.data.data.map(x => <NavLink role="listitem" key={x.id} to={`/clients/${x.id}`}><span><strong>{x.name}</strong><small>{x.code}</small></span><span>{x.type?.replaceAll('_', ' ')}</span><span className={`status status-${String(x.status).toLowerCase()}`}>{x.status}</span><span>{x.city || x.province || 'Location unavailable'}</span></NavLink>)}</div>}
    <div className="pagination"><span>Page {page}</span><button disabled={page === 1} onClick={() => move(page - 1)}>Previous</button><button disabled={(query.data?.data.length || 0) < 20} onClick={() => move(page + 1)}>Next</button></div>
  </section>
}
function ClientDetail() {
  const { id = '' } = useParams(); const user = useOutletContext<User>(); const cache = useQueryClient(); const [editing, setEditing] = useState(false); const [archiving, setArchiving] = useState(false); const [error, setError] = useState('')
  const detail = useQuery<ClientDetail>({ queryKey: ['client', id], queryFn: () => get(`/clients/${id}`) }); const contacts = useQuery<Item[]>({ queryKey: ['client', id, 'contacts'], queryFn: () => get(`/clients/${id}/contacts`) }); const owners = useQuery<Item[]>({ queryKey: ['client', id, 'owners'], queryFn: () => get(`/clients/${id}/owners`) }); const users = useQuery<User[]>({ queryKey: ['users'], queryFn: () => get('/users'), enabled: permissions(user, 'client.assign_owner') })
  function refresh() { cache.invalidateQueries({ queryKey: ['client', id] }); cache.invalidateQueries({ queryKey: ['clients'] }) }
  const update = useMutation({ mutationFn: (data: Record<string, unknown>) => patch(`/clients/${id}`, data), onSuccess: () => { setEditing(false); setError(''); refresh() }, onError: e => setError(message(e)) })
  const archive = useMutation({ mutationFn: () => post(`/clients/${id}/archive`, { version: detail.data?.client.version }), onSuccess: () => { refresh(); setArchiving(false) }, onError: e => setError(message(e)) })
  const contact = useMutation({ mutationFn: (data: Record<string, unknown>) => post(`/clients/${id}/contacts`, data), onSuccess: () => { cache.invalidateQueries({ queryKey: ['client', id, 'contacts'] }); setError('') }, onError: e => setError(message(e)) })
  const primary = useMutation({ mutationFn: (new_owner_id: string) => post(`/clients/${id}/change-primary-owner`, { new_owner_id }), onSuccess: () => { cache.invalidateQueries({ queryKey: ['client', id, 'owners'] }); refresh() }, onError: e => setError(message(e)) })
  if (detail.isPending) return <p role="status">Loading client...</p>; if (detail.isError || !detail.data) return <p role="alert">{message(detail.error)}</p>
  const client = detail.data.client; const canUpdate = permissions(user, 'client.update'); const canArchive = permissions(user, 'client.archive'); const canOwners = permissions(user, 'client.assign_owner')
  function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); update.mutate({ ...Object.fromEntries(new FormData(e.currentTarget)), version: client.version }) }
  function addContact(e: FormEvent<HTMLFormElement>) { e.preventDefault(); contact.mutate(Object.fromEntries(new FormData(e.currentTarget))) }
  return <section className="client-detail"><NavLink className="back" to="/clients">All clients</NavLink><div className="detail-heading"><div><p className="eyebrow">{client.code}</p><h1>{client.name}</h1><p>{client.type?.replaceAll('_', ' ')} · {client.status}</p></div><div className="detail-actions">{canUpdate && <button onClick={() => setEditing(!editing)}>{editing ? 'Cancel edit' : 'Edit client'}</button>}{canArchive && client.status !== 'INACTIVE' && <button className="danger" onClick={() => setArchiving(true)}>Archive</button>}</div></div>
    {error && <p role="alert">{error}</p>}{editing && <form className="card client-edit" onSubmit={save}><label>Name<input name="name" required defaultValue={client.name} /></label><label>Type<select name="type" defaultValue={client.type}>{clientTypes.map(x => <option key={x}>{x}</option>)}</select></label><label>Status<select name="status" defaultValue={client.status}>{clientStatuses.map(x => <option key={x}>{x}</option>)}</select></label><label>Province<input name="province" defaultValue={client.province} /></label><label>City<input name="city" defaultValue={client.city} /></label><label>Address<input name="address" defaultValue={client.address} /></label><button disabled={update.isPending}>{update.isPending ? 'Saving...' : 'Save changes'}</button></form>}
    <div className="detail-grid"><section className="panel"><h2>Operational picture</h2><dl>{Object.entries(detail.data.summary || {}).map(([k, v]) => <div key={k}><dt>{k.replaceAll('_', ' ')}</dt><dd>{String(v)}</dd></div>)}{detail.data.health && <div><dt>Health</dt><dd>{label(detail.data.health)} {String(detail.data.health.score || '')}</dd></div>}</dl></section><section className="panel"><h2>Owners</h2>{owners.isPending ? <p>Loading...</p> : owners.data?.length ? <ul className="compact-list">{owners.data.map(x => <li key={x.id}><strong>{String(x.user_name || x.name || x.user_id)}</strong><small>{String(x.owner_type)}</small></li>)}</ul> : <p>No owners assigned.</p>}{canOwners && <form onSubmit={e => { e.preventDefault(); const owner = String(new FormData(e.currentTarget).get('new_owner_id')); if (owner) primary.mutate(owner) }}><label>Primary owner<select name="new_owner_id" required defaultValue=""><option value="" disabled>Select user</option>{users.data?.map(x => <option key={x.id} value={x.id}>{x.name} ({x.email})</option>)}</select></label><button disabled={primary.isPending || users.isPending}>{primary.isPending ? 'Changing...' : 'Change primary owner'}</button>{users.isError && <p role="alert">Users unavailable: {message(users.error)}</p>}</form>}</section><section className="panel"><h2>Contacts</h2>{contacts.isPending ? <p>Loading...</p> : contacts.data?.length ? <ul className="compact-list">{contacts.data.map(x => <li key={x.id}><strong>{label(x)}</strong><small>{String(x.email || x.phone || '')}</small></li>)}</ul> : <p>No contacts recorded.</p>}{canUpdate && <form onSubmit={addContact}><label>Name<input name="name" required /></label><label>Email<input name="email" type="email" /></label><label>Phone<input name="phone" /></label><label>Role<input name="role" /></label><button disabled={contact.isPending}>{contact.isPending ? 'Adding...' : 'Add contact'}</button></form>}</section></div>
    {archiving && <div className="dialog-backdrop" role="presentation"><section className="dialog" role="alertdialog" aria-modal="true" aria-labelledby="archive-title"><h2 id="archive-title">Archive {client.name}?</h2><p>Archived clients leave active service. This action is traceable.</p><div><button className="danger" autoFocus disabled={archive.isPending} onClick={() => archive.mutate()}>{archive.isPending ? 'Archiving...' : 'Archive client'}</button><button className="secondary" onClick={() => setArchiving(false)}>Cancel</button></div></section></div>}
  </section>
}
function Issues() { const [open, setOpen] = useState(false); return <><List path="/issues" title="Issues" create={<button onClick={() => setOpen(!open)}>New issue</button>} render={x => <NavLink to={`/issues/${x.id}`}><strong>{label(x)}</strong><small>{String(x.status || '')} {String(x.severity || '')}</small></NavLink>} />{open && <Create path="/issues" done={() => setOpen(false)} fields={[{ name: 'client_id', label: 'Client ID' }, { name: 'title', label: 'Title' }, { name: 'description', label: 'Description' }, { name: 'severity', label: 'Severity', options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] }]} />}</> }
const actions: Record<string, string> = { REPORTED: 'triage', TRIAGED: 'start-investigation', INVESTIGATING: 'start-development', IN_DEVELOPMENT: 'mark-qa', QA: 'mark-released', RELEASED: 'start-follow-up', FOLLOW_UP: 'close' }
function IssueDetail() { const { id = '' } = useParams(); const cache = useQueryClient(); const q = useQuery<Item>({ queryKey: ['issue', id], queryFn: () => get(`/issues/${id}`) }); const action = useMutation({ mutationFn: (name: string) => post(`/issues/${id}/${name}`, { version: q.data?.version }), onSuccess: () => cache.invalidateQueries({ queryKey: ['issue', id] }) }); if (q.isPending) return <p role="status">Loading...</p>; if (q.isError || !q.data) return <p role="alert">{message(q.error)}</p>; const next = actions[String(q.data.status)]; return <section><h1>{label(q.data)}</h1><dl>{Object.entries(q.data).filter(([k]) => ['status', 'severity', 'description', 'version'].includes(k)).map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl>{next && <button disabled={action.isPending} onClick={() => action.mutate(next)}>{action.isPending ? 'Updating...' : next.replaceAll('-', ' ')}</button>}{action.isError && <p role="alert">{message(action.error)}</p>}</section> }
function Releases() { const [open, setOpen] = useState(false); return <><List path="/releases" title="Releases" create={<button onClick={() => setOpen(!open)}>New release</button>} />{open && <Create path="/releases" done={() => setOpen(false)} fields={[{ name: 'version', label: 'Version' }, { name: 'title', label: 'Title' }, { name: 'summary', label: 'Summary' }]} />}</> }
function Operations({ followUps = false }: { followUps?: boolean }) { const path = followUps ? '/follow-ups' : '/handoffs'; return <List path={path} title={followUps ? 'Follow-ups' : 'Handoffs'} render={x => <><strong>{label(x)}</strong><small>{String(x.status || '')}</small></>} /> }
export default function App() { return <QueryClientProvider client={client}><Routes><Route path="/login" element={<Login />} /><Route element={<Shell />}><Route path="/dashboard" element={<Dashboard />} /><Route path="/clients" element={<Clients />} /><Route path="/clients/:id" element={<ClientDetail />} /><Route path="/issues" element={<Issues />} /><Route path="/issues/:id" element={<IssueDetail />} /><Route path="/releases" element={<Releases />} /><Route path="/handoffs" element={<Operations />} /><Route path="/follow-ups" element={<Operations followUps />} /></Route><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></QueryClientProvider> }
